[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["None"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
flask = "^3.1.0"

[[tool.poetry.source]]
name = "pypi-proxy"
url = "http://user:password@host.docker.internal:PORT/pypi/"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
